version: '3'
services:

  postgresql:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=telm
      - POSTGRES_DB=telm
      - POSTGRES_PORT=5342
      - POSTGRES_PASSWORD=SuperTajneHaslo
    volumes:
      - ${APP_VOLUME:-./volume}/pgdata:/var/lib/postgresql/data
    expose:
      - '5432'

  redis:
    image: redis:6-alpine
    environment:
      - APP_SECRET
    expose:
      - '6379'

  node:
    image: 'telm-project-node:${APP_VERSION:-latest}'
    deploy:
      replicas: 2
    environment:
      - APP_SECRET
      - APP_PORT=8080
      - APP_PGUSER
      - APP_PGDATABASE
      - APP_PGPASSWD
      - APP_PGPORT=5432
      - APP_PGHOST=postgresql
      - APP_REDISURL=redis://redis:6379
    depends_on:
      - postgresql
      - redis
    expose:
      - '8080'

  nginx:
    image: nginx:1.18-alpine
    volumes:
      - ./nginx.nginx:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    ports:
      - '8080:8080'
