version: '3'
services:

  postgresql:
    image: postgres:12-alpine
    volumes:
      - ./volume/pgdata:/var/lib/postgresql/data
    env_file:
      - POSTGRES_USER=telm
      - POSTGRES_DB=telm
      - POSTGRES_PORT=5342
      - POSTGRES_PASSWORD=SuperTajneHaslo
    ports:
      - '5001:5432'

  redis:
    image: redis
    ports:
      - "5002:6379"